export const heroes = [
  { name: "플리트비체", star: "3성", element: "화속성" },
  { name: "라피스", star: "3성", element: "광속성" },
  { name: "마리나", star: "3성", element: "수속성" },
  { name: "아라벨", star: "3성", element: "암속성" },
  { name: "아이돌 에바", star: "3성", element: "무속성" },
  { name: "바리", star: "3성", element: "지속성" },
  { name: "루피나", star: "3성", element: "암속성" },
  { name: "란", star: "3성", element: "무속성" },
  { name: "유진", star: "3성", element: "광속성" },
  { name: "티니아", star: "3성", element: "지속성" },
  { name: "비슈바크", star: "3성", element: "화속성" },
  { name: "나리", star: "3성", element: "무속성" },
  { name: "비앙카", star: "3성", element: "수속성" },
  { name: "오그마", star: "3성", element: "암속성" },
  { name: "알레프", star: "3성", element: "지속성" },
  { name: "미야", star: "3성", element: "화속성" },
  { name: "미래 공주", star: "3성", element: "광속성" },
  { name: "가람", star: "3성", element: "수속성" },
  { name: "베스", star: "3성", element: "암속성" },
  { name: "루", star: "3성", element: "지속성" },
  { name: "가브리엘", star: "3성", element: "광속성" },
  { name: "린", star: "3성", element: "화속성" },
  { name: "미래기사", star: "3성", element: "무속성" },
  { name: "베로니카", star: "3성", element: "수속성" },
  { name: "녹시아", star: "3성", element: "암속성" },
  { name: "메이릴", star: "3성", element: "지속성" },
  { name: "MK.99", star: "3성", element: "광속성" },
  { name: "리리스", star: "3성", element: "암속성" },
  { name: "루시", star: "3성", element: "화속성" },
  { name: "수소히", star: "3성", element: "무속성" },
  { name: "수유즈", star: "3성", element: "수속성" },
  { name: "엘레노아", star: "3성", element: "광속성" },
  { name: "신틸라", star: "3성", element: "화속성" },
  //----------------------3성-----------------------
  { name: "기사", star: "2성", element: "무속성" },
  { name: "에바", star: "2성", element: "광속성" },
  { name: "엘비라", star: "2성", element: "화속성" },
  { name: "하얀 야수", star: "2성", element: "수속성" },
  { name: "카리나", star: "2성", element: "암속성" },
  { name: "로레인", star: "2성", element: "무속성" },
  { name: "라비", star: "2성", element: "화속성" },
  { name: "파비", star: "2성", element: "수속성" },
  { name: "아오바", star: "2성", element: "지속성" },
  { name: "그레모리", star: "2성", element: "암속성" },
  { name: "레이첼", star: "2성", element: "수속성" },
  { name: "헤카테", star: "2성", element: "지속성" },
  { name: "코코", star: "2성", element: "수속성" },
  { name: "마리안", star: "2성", element: "지속성" },
  { name: "소히", star: "2성", element: "광속성" },
  { name: "페이&메이", star: "2성", element: "광속성" },
  { name: "마빈", star: "2성", element: "지속성" },
  { name: "크레이그", star: "2성", element: "지속성" },
  { name: "아카유키", star: "2성", element: "화속성" },
  { name: "란팡", star: "2성", element: "무속성" },
  { name: "유즈", star: "2성", element: "암속성" },
  { name: "아이샤", star: "2성", element: "광속성" },
  { name: "샤피라", star: "2성", element: "암속성" },
  { name: "돌프", star: "2성", element: "화속성" },
  { name: "에이미", star: "2성", element: "무속성" },
  { name: "기르가스", star: "2성", element: "화속성" },
  { name: "캐서린", star: "2성", element: "수속성" },
    //----------------------2성-----------------------
  { name: "리에", star: "2성", element: "무속성" },
  { name: "네바", star: "2성", element: "광속성" },
  { name: "린다", star: "1성", element: "무속성" },
  { name: "밥", star: "1성", element: "무속성" },
  { name: "하이퍼", star: "1성", element: "화속성" },
  { name: "마리아", star: "1성", element: "화속성" },
  { name: "리사", star: "1성", element: "지속성" },
  { name: "레아", star: "1성", element: "지속성" },
  { name: "제이", star: "1성", element: "무속성" },
  { name: "드래곤", star: "1성", element: "광속성" },
  { name: "블레이드", star: "1성", element: "수속성" },
  { name: "미나", star: "1성", element: "화속성" },
  { name: "동태", star: "1성", element: "암속성" },
  { name: "페기", star: "1성", element: "암속성" },
  { name: "에일리", star: "1성", element: "화속성" },
  { name: "오렐리", star: "1성", element: "암속성" },
  { name: "캉", star: "1성", element: "광속성" },
  { name: "아가사", star: "1성", element: "수속성" },
  { name: "다빈치", star: "1성", element: "수속성" },
  { name: "케이트", star: "1성", element: "지속성" },
  { name: "조이", star: "1성", element: "암속성" },
  { name: "리오", star: "1성", element: "지속성" },
  { name: "나이언", star: "1성", element: "무속성" },
  { name: "마티 주니어", star: "1성", element: "지속성" },
    //----------------------1성-----------------------
  { name: "none", star: "none", element: "none" },
];

export const heroesName = [
  "플리트비체",
  "라피스",
  "마리나",
  "아라벨",
  "아이돌 에바",
  "바리",
  "루피나",
  "란",
  "유진",
  "티니아",
  "비슈바크",
  "나리",
  "비앙카",
  "오그마",
  "알레프",
  "미야",
  "미래 공주",
  "가람",
  "베스",
  "루",
  "가브리엘",
  "린",
  "미래기사",
  "베로니카",
  "녹시아",
  "메이릴",
  "MK.99",
  "리리스",
  "루시",
  "수소히",
  "수유즈",
  "엘레노아",
  "신틸라",
    //----------------------3성-----------------------
  "기사",
  "에바",
  "엘비라",
  "하얀 야수",
  "카리나",
  "로레인",
  "라비",
  "파비",
  "아오바",
  "그레모리",
  "레이첼",
  "헤카테",
  "코코",
  "마리안",
  "소히",
  "페이&메이",
  "마빈",
  "크레이그",
  "아카유키",
  "란팡",
  "유즈",
  "아이샤",
  "샤피라",
  "돌프",
  "에이미",
  "기르가스",
  "캐서린",
  "리에",
  "네바",
    //----------------------2성-----------------------
  "린다",
  "밥",
  "하이퍼",
  "마리아",
  "리사",
  "레아",
  "제이",
  "드래곤",
  "블레이드",
  "미나",
  "동태",
  "페기",
  "에일리",
  "오렐리",
  "캉",
  "아가사",
  "다빈치",
  "케이트",
  "조이",
  "리오",
  "나이언",
  "마티 주니어",
];

export default heroes;
