export const heroesInfo = {
  0: { name: "플리트비체", star: "3성", element: "화속성" },
  1: { name: "라피스", star: "3성", element: "광속성" },
  2: { name: "마리나", star: "3성", element: "수속성" },
  3: { name: "아라벨", star: "3성", element: "암속성" },
  4: { name: "아이돌 에바", star: "3성", element: "무속성" },
  5: { name: "바리", star: "3성", element: "지속성" },
  6: { name: "루피나", star: "3성", element: "암속성" },
  7: { name: "란", star: "3성", element: "무속성" },
  8: { name: "유진", star: "3성", element: "광속성" },
  9: { name: "티니아", star: "3성", element: "지속성" },
  10: { name: "비슈바크", star: "3성", element: "화속성" },
  11: { name: "나리", star: "3성", element: "무속성" },
  12: { name: "비앙카", star: "3성", element: "수속성" },
  13: { name: "오그마", star: "3성", element: "암속성" },
  14: { name: "알레프", star: "3성", element: "지속성" },
  15: { name: "미야", star: "3성", element: "화속성" },
  16: { name: "미래 공주", star: "3성", element: "광속성" },
  17: { name: "가람", star: "3성", element: "수속성" },
  18: { name: "베스", star: "3성", element: "암속성" },
  19: { name: "루", star: "3성", element: "지속성" },
  20: { name: "가브리엘", star: "3성", element: "광속성" },
  21: { name: "린", star: "3성", element: "화속성" },
  22: { name: "미래기사", star: "3성", element: "무속성" },
  23: { name: "베로니카", star: "3성", element: "수속성" },
  24: { name: "녹시아", star: "3성", element: "암속성" },
  25: { name: "메이릴", star: "3성", element: "지속성" },
  26: { name: "MK.99", star: "3성", element: "광속성" },
  27: { name: "리리스", star: "3성", element: "암속성" },
  28: { name: "루시", star: "3성", element: "화속성" },
  29: { name: "수소희", star: "3성", element: "무속성" },
  30: { name: "수유즈", star: "3성", element: "수속성" },
  31: { name: "엘레노아", star: "3성", element: "광속성" },
  32: { name: "여기사", star: "2성", element: "무속성" },
  33: { name: "에바", star: "2성", element: "광속성" },
  34: { name: "엘비라", star: "2성", element: "화속성" },
  35: { name: "하얀 야수", star: "2성", element: "수속성" },
  36: { name: "카리나", star: "2성", element: "암속성" },
  37: { name: "로레인", star: "2성", element: "무속성" },
  38: { name: "라비", star: "2성", element: "화속성" },
  39: { name: "파비", star: "2성", element: "수속성" },
  40: { name: "아오바", star: "2성", element: "지속성" },
  41: { name: "그레모리", star: "2성", element: "암속성" },
  42: { name: "레이첼", star: "2성", element: "수속성" },
  43: { name: "헤카테", star: "2성", element: "지속성" },
  44: { name: "코코", star: "2성", element: "수속성" },
  45: { name: "마리안", star: "2성", element: "지속성" },
  46: { name: "소희", star: "2성", element: "광속성" },
  47: { name: "페이&메이", star: "2성", element: "광속성" },
  48: { name: "마빈", star: "2성", element: "지속성" },
  49: { name: "크레이그", star: "2성", element: "지속성" },
  50: { name: "아카유키", star: "2성", element: "화속성" },
  51: { name: "란팡", star: "2성", element: "무속성" },
  52: { name: "유즈", star: "2성", element: "암속성" },
  53: { name: "아이샤", star: "2성", element: "광속성" },
  54: { name: "샤피라", star: "2성", element: "암속성" },
  55: { name: "돌프", star: "2성", element: "화속성" },
  56: { name: "에이미", star: "2성", element: "무속성" },
  57: { name: "기르가스", star: "2성", element: "화속성" },
  58: { name: "캐서린", star: "2성", element: "수속성" },
  59: { name: "리에", star: "2성", element: "무속성" },
  60: { name: "네바", star: "2성", element: "광속성" },
  61: { name: "린다", star: "3성", element: "무속성" },
  62: { name: "밥", star: "3성", element: "무속성" },
  63: { name: "하이퍼", star: "3성", element: "화속성" },
  64: { name: "마리아", star: "3성", element: "화속성" },
  65: { name: "리사", star: "3성", element: "지속성" },
  66: { name: "레아", star: "3성", element: "지속성" },
  67: { name: "제이", star: "3성", element: "무속성" },
  68: { name: "드래곤", star: "3성", element: "광속성" },
  69: { name: "블레이드", star: "3성", element: "수속성" },
  70: { name: "미나", star: "3성", element: "화속성" },
  71: { name: "동태", star: "3성", element: "암속성" },
  72: { name: "페기", star: "3성", element: "암속성" },
  73: { name: "에일리", star: "3성", element: "화속성" },
  74: { name: "오렐리", star: "3성", element: "암속성" },
  75: { name: "캉", star: "3성", element: "광속성" },
  76: { name: "아가사", star: "3성", element: "수속성" },
  77: { name: "다빈치", star: "3성", element: "수속성" },
  78: { name: "케이트", star: "3성", element: "지속성" },
  79: { name: "조이", star: "3성", element: "암속성" },
  80: { name: "리오", star: "3성", element: "지속성" },
  81: { name: "나이언", star: "3성", element: "무속성" },
  82: { name: "마티 주니어", star: "3성", element: "지속성" },
  83: { name: "none", star: "none", element: "none" },
};

export const heroesName = {
  0: "플리트비체",
  1: "라피스",
  2: "마리나",
  3: "아라벨",
  4: "아이돌 에바",
  5: "바리",
  6: "루피나",
  7: "란",
  8: "유진",
  9: "티니아",
  10: "비슈바크",
  11: "나리",
  12: "비앙카",
  13: "오그마",
  14: "알레프",
  15: "미야",
  16: "미래 공주",
  17: "가람",
  18: "베스",
  19: "루",
  20: "가브리엘",
  21: "린",
  22: "미래기사",
  23: "베로니카",
  24: "녹시아",
  25: "메이릴",
  26: "MK.99",
  27: "리리스",
  28: "루시",
  29: "수소희",
  30: "수유즈",
  31: "엘레노아",
  32: "여기사",
  33: "에바",
  34: "엘비라",
  35: "하얀 야수",
  36: "카리나",
  37: "로레인",
  38: "라비",
  39: "파비",
  40: "아오바",
  41: "그레모리",
  42: "레이첼",
  43: "헤카테",
  44: "코코",
  45: "마리안",
  46: "소희",
  47: "페이",
  48: "마빈",
  49: "크레이그",
  50: "아카유키",
  51: "란팡",
  52: "유즈",
  53: "아이샤",
  54: "샤피라",
  55: "돌프",
  56: "에이미",
  57: "기르가스",
  58: "캐서린",
  59: "리에",
  60: "네바",
  61: "린다",
  62: "밥",
  63: "하이퍼",
  64: "마리아",
  65: "리사",
  66: "레아",
  67: "제이",
  68: "드래곤",
  69: "블레이드",
  70: "미나",
  71: "동태",
  72: "페기",
  73: "에일리",
  74: "오렐리",
  75: "캉",
  76: "아가사",
  77: "다빈치",
  78: "케이트",
  79: "조이",
  80: "리오",
  81: "나이언",
  82: "마티 주니어",
};

export default heroesInfo;
